# Generated by Django 5.2.1 on 2025-05-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('sira', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('hazirlaniyor', 'Hazırlanıyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='beklemede', max_length=20)),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to='cafe.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunler/')),
                ('stokta', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='cafe.kategori')),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='SiparisUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField(default=1)),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.urun')),
            ],
        ),
        migrations.AddField(
            model_name='siparis',
            name='urunler',
            field=models.ManyToManyField(through='cafe.SiparisUrun', to='cafe.urun'),
        ),
    ]
