# Generated by Django 5.2.1 on 2025-05-09 11:00

import cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_kategori_siparis_urun_siparisurun_siparis_urunler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=cafe.models.urun_resim_yolu),
        ),
    ]
