# Generated by Django 5.2.1 on 2025-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_kategori_isim_alter_urun_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='musteri',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='urunler',
        ),
        migrations.AddField(
            model_name='siparis',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siparis',
            name='masa_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siparis',
            name='odeme_durum',
            field=models.CharField(choices=[('bekliyor', 'Ödeme Bekliyor'), ('odendi', 'Ödendi'), ('iptal', 'İptal')], default='bekliyor', max_length=20),
        ),
        migrations.AddField(
            model_name='siparis',
            name='odeme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siparisurun',
            name='toplam_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
