# Generated by Django 5.2.1 on 2025-05-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_siparis_musteri_remove_siparis_urunler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisurun',
            name='siparis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparis_urunleri', to='cafe.siparis'),
        ),
    ]
